export enum DataActionType {
    BEFORE_SELECT = 'BEFORE_SELECT',
    AFTER_SELECT = 'AFTER_SELECT',
    BEFORE_DESELECT = 'BEFORE_DESELECT',
    AFTER_DESELECT = 'AFTER_DESELECT',
    BEFORE_CREATE = 'BEFORE_CREATE',
    AFTER_CREATE = 'AFTER_CREATE',
    BEFORE_UPDATE = 'BEFORE_UPDATE',
    AFTER_UPDATE = 'AFTER_UPDATE',
    BEFORE_DELETE = 'BEFORE_DELETE',
    AFTER_DELETE = 'AFTER_DELETE'
}
